### ISSUE TITLE
How to handle nested BoolExpr?

### ISSUE THREAD

**Issue by a1880** [deiruch/SATInterface#1]
Dear Simon,

Thank you for your SATinterface. It does look very promising.

During my first experiments I encountered overflows with nested Boolean expressions.
It seems that SATInterface is not applying any [Tseytin encoding](https://en.wikipedia.org/wiki/Tseytin_transformation). This results in an explosion of the resulting [CNF](https://en.wikipedia.org/wiki/Conjunctive_normal_form).

I used the following to introduce auxiliary switching variables and get around this problem:

```
static int noOfAuxVariables = 0;

static BoolVar AuxVariable()
{
    return new BoolVar(m, $"aux{++noOfAuxVariables}");
}

static BoolExpr And3(BoolExpr f, BoolExpr g, BoolExpr d)
{
    var a = AndExpr.Create(f, g, d);
    var aux = AuxVariable();

    m.AddConstr(aux == a);

    return aux;
}

static BoolExpr Odd(BoolExpr[] x)
{
    int len = x.Length;

   switch(len)
   {
        case 0: return BoolExpr.False;
        case 1: return x[0];
        case 2: return x[0] != x[1];
        default:
            BoolExpr o0 = Odd(x.Where((y, i) => i % 2 == 0).ToArray());
            BoolExpr o1 = Odd(x.Where((y, i) => i % 2 == 1).ToArray());
            BoolVar v0 = AuxVariable();
            BoolVar v1 = AuxVariable();

            m.AddConstr(v0 == o0);
            m.AddConstr(v1 == o1);

            return v0 != v1;
    }
}

```

Am I missing something? Or is this the way to go?

Greetings!

Axel

**Comment by deiruch** [comment]
Hi Axel

Great that you find the project useful!

Currently, the project does not perform optimizations on your behalf: It does not eliminate common subexpressions, or pick the best encoding for linear expressions. But you can always force Tseytin encoding with the `.Flatten(model)` for any expression. For example:

```
var orResult = OrExpression.Create(v0, v1, v2, v3, v4).Flatten();
```

this also works in combination with operator overloading:
```
var orResult = (v0 | v1 | v2 | v3).Flatten();
```

Does this solve the problem?

Cheers
Simon

**Comment by deiruch** [comment]
By the way: I just released 2.1.10 which should give you better performance for expression hierarchies. Let me know whether things have improved.

**Comment by a1880** [comment]
Thanks! I'll try Flatten()

**Comment by a1880** [comment]
Hi Simon,
Actually, the new 2.1.10 release appears to be somewhat slower than the previous one, at least for my example. The runtime went up from 0.8s to 7.8s. I then compared `Flatten()` against my Tseytin encoding with auxiliary variables. Both variants show similar runtimes, but `Flatten()` looks easier to use.

I used [bc2cnf](https://users.ics.aalto.fi/tjunttil/circuits/) to translate Boolean circuits to CNF. Later on, I developed my own tools, a SAT Solver interface and a bc2cnf clone. The bc Boolean circuit file is generated by hand or by a suitable program. I start the selected SAT solver as external process. The CNF is provided as file, and the solution is read from the solver output. This was my reason to extend CaDiCaL by a new option which allows a named result file. I do like your CaDiCaL "Platform Adaption Layer", including colored text output and timeout. But your CaDiCaL does not allow to store the solution in a separate file without using `tee `pipeline tricks.

I noticed that you implemented several cardinality constraints. In this respect, bc2cnf might be interesting for you. It also features quite a versatile cardinality function and a lot of circuit translation optimizations.

Greetings,

Axel

**Comment by deiruch** [comment]
Thanks for the bc2cnf reference, something I'll look into! Other things I might implement, if time allows:

- Common subexpression elimination
- Reformulation of certain linear constraints with commander encodings
- Automatic flattening when appropriate

If you want to use CaDiCaL in your applications, you might find the [CaDiCaL C# Interface](https://github.com/deiruch/SATInterface/blob/master/SATInterface/CaDiCaL.cs) from this project useful. In case you didn't find it already, there's a [Win32 port of CaDiCal](https://github.com/deiruch/cadical) that you could use, where you can pipe the results to a file, as usual.

If you can share it, I'd be interested in the 0.8s -> 7.8s regression case. I'd like to add it as a test case to improve the performance.

**Comment by a1880** [comment]
I'll send my example to you via mail.

I am hesitant to extract the solution from CaDiCaL stdout. Log and solution should be kept separate. Therefore, I am using my own CaDiCaL Windows port.
