### ISSUE TITLE
New promising SAT solvers

### ISSUE THREAD

**Issue by a1880** [deiruch/SATInterface#2]
Hi Felix,

Just in case you have some free time to spend:

I ported SAT solvers [gimsatul](https://github.com/arminbiere/gimsatul) and [seqfrost ](https://github.com/muhos/SeqFROST)to Microsoft Windows VC++ 2022.
Both do look promising and might be a worthwhile addition to your SATInterface.

Best greetings!

Axel

**Comment by deiruch** [comment]
Great idea! Where can I find the solver ports?

**Comment by benjaminbartsch** [comment]
Wow great!
